moviecollector/main_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('movies/', views.movie_index, name='movie-index'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie-detail'),
    path('movies/create/', views.MovieCreate.as_view(), name='movie-create'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie-update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie-delete'),
    path(
        'movies/<int:movie_id>/add-critic/',
        views.add_critic,
        name='add-critic'
    ),
    path('accounts/signup/', views.signup, name='signup'),
]

moviecollector/moviecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

moviecollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
SOURCES = (
    ('I', 'IMDB'),
    ('RT', 'Rotten Tomatoes'),
    ('M', 'Metacritic')
)

class Movie(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    director = models.CharField(max_length=100)
    year = models.IntegerField()

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('movie-detail', kwargs={'movie_id': self.id})
    
class Critic(models.Model):
    source = models.CharField(
        max_length=50,
        choices=SOURCES,
        default=SOURCES[0][0]
    )
    rating = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
    ) 
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'Rating from {self.get_source_display()}: {self.rating}'

moviecollector/main_app/forms.py
from django import forms
from .models import Critic

# was looking for widgets/improved ways to store different decimal type numbers for the ratings, 
# so looked at both django docs and research on google, etc

class CriticForm(forms.ModelForm):
    class Meta:
        model = Critic
        fields = ['source', 'rating']
        widgets = {
            'rating': forms.NumberInput(attrs={'step': '0.01', 'min': '0', 'max': '100'}),
        }

    def clean_rating(self):
        rating = self.cleaned_data.get('rating')
        source = self.cleaned_data.get('source')

       
        if source == 'I' and rating is not None:
                return round(rating, 1)
            
        elif source in ['RT', 'M'] and rating is not None:
                return round(rating)
            
        return rating

moviecollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from .models import Movie
from .forms import CriticForm

# Create your views here.



class Home(LoginView):
    template_name = 'home.html'


def about(request):
    return render(request, 'about.html')

@login_required
def movie_index(request):
    movies = Movie.objects.filter(user=request.user)
    return render(request, 'movies/index.html', {'movies': movies})

@login_required
def movie_detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    critic_form = CriticForm()
    return render(request, 'movies/detail.html', {
        'movie': movie, 'critic_form': critic_form
    })

@login_required
def add_critic(request, movie_id):
    form = CriticForm(request.POST)
    if form.is_valid():
        new_critic = form.save(commit=False)
        new_critic.movie_id = movie_id
        new_critic.save()
    return redirect('movie-detail', movie_id=movie_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('movie-index')
        else:
            error_message = 'Invalid sign up - try again'
            
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class MovieCreate(LoginRequiredMixin, CreateView):
    model = Movie
    fields = ['name', 'genre', 'description', 'director', 'year']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class MovieUpdate(LoginRequiredMixin, UpdateView):
    model = Movie
    fields = ['genre', 'description', 'director', 'year']

class MovieDelete(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = '/movies/'

moviecollector/main_app/templates/about.html
{% extends 'base.html' %} 

{% block content %}

<main class="page-background">
    <h1>Movie Collection Site</h1>
    <hr />
    <p class="page-content">
        Storing all your favorite movies on the site with some info about each one!
    </p>
</main>
  

{% endblock %}

moviecollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/camera.webp' %}" />
    <title>My Movie Collection</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img class="main-logo" src="{% static 'images/camera.webp' %}" alt="The Movie Collection Logo" />
        </a>
      </div>
      <nav>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'movie-index' %}">All Movies</a></li>
            <li><a href="{% url 'movie-create' %}">Add a Movie</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
                <form id="logout-form" method="post" action="{% url 'logout' %}">
                  {% csrf_token %}
                  <button type="submit">Log out</button>
                </form>
              </li>
            {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>

moviecollector/main_app/templates/home.html
{% extends 'base.html' %} {% load static %}

{% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}
<main>
<section class="logo-container">
  <div class="movie-container">
    <h1 class="home-screen-title">Movie Collection</h1>
    <img class="Page-logo"
      src="{% static 'images/cinemaseats.jpg' %}"
      alt="The Movie Collector Logo"
    />
  </div>
</section>
{% if not user.is_authenticated %}
  <section class="login-container">
    <form action="{% url 'home' %}" method="post" class="login">
      <h1 class="login-header">Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}
</main>
{% endblock %}

moviecollector/main_app/templates/main_app/movie_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
<div class="page-header">
  <h1 class="confirm-question-top">Delete Movie?</h1>
  <img class="delete-screen-img" src="{% static 'images/movie-projector.webp' %}" alt="A movie projector" />
</div>

<h2 class="confirm-question" >Are you sure you want to delete {{ movie.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'movie-detail' movie.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

moviecollector/main_app/templates/main_app/movie_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<main class="page-background">
<div class="page-header">
    {% if movie %}
      <h1 class="edit-movie-words">Edit {{ movie.name }}</h1>
    {% else %}
      <h1 class="edit-movie-words">Add a Movie</h1>
    {% endif %}
  </div>
  <img class="edit-screen-img" src="{% static 'images/cassette-image.webp' %}" alt="A video casette" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit</button>
</form>
</main>
{% endblock %}

moviecollector/main_app/templates/movies/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/movies/movie-detail.css' %}" />
{% endblock %} 
{% block content %}
<main class="page-background">
<section class="movie-container">
  <div class="movie-img">
    <img src="{% static 'images/popcorn-theatre.jpg' %}" alt="popcorn theatre" />
  </div>
</div>
<div class="movie-info">
<h2 class="'movie-title"><strong> {{ movie.name }} </strong></h2>
<p class="movie-genre"> <strong>{{ movie.genre }}</strong> </p>
<p class="movie-details"> <strong> {{ movie.director }}, {{ movie.year }} </strong></p>
<p class="movie-description"> <em> {{ movie.description }}</em></p>

<div class="movie-actions">
    <a href="{% url 'movie-update' movie.id %}" class="btn warn">Edit</a>
    <a href="{% url 'movie-delete' movie.id %}" class="btn danger">Delete</a>
  </div>
</div>
</section>
<div class="critics-container">
    <section class="critics">
      <div class="subsection-title">
        <img class="critic-logo" src="{% static 'images/camera.webp' %}" alt="A black and white old film movie camera" />
        <h2 class="critic-header">Ratings</h2>
      </div>
      <h3>Add a Critic Rating</h3>
      <form
        action="{% url 'add-critic' movie.id %}"
        method="post"
        class="subsection-content"
        autocomplete="off"
        >
    {% csrf_token %} 
    {{ critic_form.as_p }}
  <button type="submit" class="btn submit">Add Rating</button>
</form>

      <h3>Critics Ratings</h3>
      <table>
        <thead>
          <tr>
            <th class="critic-label">Source</th>
            <th class="critic-label">Rating</th>
          </tr>
        </thead>
        <tbody class="critic-info-container">
          {% for critic in movie.critic_set.all %}
            <tr>
              <td>{{critic.get_source_display}}</td>
              <td>
                {% if critic.source == 'I' %}
                    {{ critic.rating|floatformat:1 }}
                {% elif critic.source == 'RT' %}
                    {{ critic.rating|floatformat:0 }}
                {% elif critic.source == 'M' %}
                    {{ critic.rating|floatformat:0 }}
                {% else %}
                    {{ critic.rating }}
                {% endif %}
              </td>
              
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
    </section>
  </div>
</main>
{% endblock %}

moviecollector/main_app/templates/movies/index.html
{% extends 'base.html' %} {% load static %}

{% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/movies/movie-index.css' %}"
/>
{% endblock %}

{% block content %}
<main class="page-background">
    <div class="full-width-banner">
    <h1>Movies</h1>
</div>
<section class="card-container">
  {% for movie in movies %}
  <div class="card">
    <a href="{% url 'movie-detail' movie.id %}">
    <div class="card-content">
      <div class="card-img-container">
        <img
          src="{% static 'images/popcorn-theatre.jpg' %}"
          alt="movie image"
        />
      </div>
      <div class="movie-info">
      <h2 class="'movie-title"><strong> {{ movie.name }} </strong></h2>
      <p class="movie-genre"> <strong>{{ movie.genre }}</strong> </p>
      <p class="movie-details"> <strong> {{ movie.director }}, {{ movie.year }} </strong></p>
      <p class="movie-description"><em> {{ movie.description }} </em></p>
    </div>
    </a>
    </div>
  </div>
  {% endfor %}
</section>
</main>
{% endblock %}

moviecollector/main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img class="edit-screen-img" src="{% static 'images/cassette-image.webp' %}" alt="A video casette" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}